[project]
name = "drf-p33-channels"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "channels[daphne]>=4.3.2",
    "django>=5.2.8",
    "ujson>=5.11.0",
]
